### ISSUE TITLE
Support new thread creation

### ISSUE THREAD

**Issue by acaloiaro** [jpbruinsslot/slack-term#217]
I often want to create new threads within `slack-term`. 

I've proposed a new key mapping `m` that toggles message IDs to be displayed so that users are able to use the `/thread` slash command to create new threads from any non-threaded message, in addition to replying to existing threads. 

E.g. 
> [13/10 16:02] bStUeg \<adriano\> Hello channel!

`/thread bStUeg Hello adriano!`

> [13/10 16:02] bStUeg \<adriano\> Hello channel! 
> [13/10 22:59]   \<adriano\> Hello adriano!

**Comment by acaloiaro** [comment]
FYI I have a branch spoorting `/edit` (for editing messages) built on top of this one.

**Comment by samueldy** [comment]
I too really find it helpful to organize messages into threads as well. I really appreciate `slack-term` as much of my work involves headless machines and low-memory environments where I can't run the full Electron client, but this is one of the things that keeps me from switching completely to `slack-term`.
